version: '3.9'

services:
  backend:
    build:
      context: ./nodejs-backend
    container_name: nodejs-backend
    ports:
      - "8080:8080"
    environment:
      - COSMOS_ENDPOINT=https://<cosmos-account>.documents.azure.com:443/
      - COSMOS_KEY=<key>
      - COSMOS_DB=<db-name>
      - COSMOS_CONTAINER=<container-name>
      - PORT=8080

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_API_URL: http://localhost:8080
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend